---
name: Go
on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic
      - name: Send coverage
        uses: codecov/codecov-action@v1
